spring:
  application:
    name: wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet?sslmode=disable
    username: wallet_api
    password: 123456
  data:
    jdbc:
      dialect: postgresql
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true

management:
  endpoints:
    web:
      base-path: /